<?php $this->headStyle()->captureStart(); ?>
div#content {
    min-height: 300pt;
}

div#content h1 {
    color: rgba(0,0,0,0.5);
    font-size: 20em;
    font-weight: bold;
    text-align: right;
    margin: 0pt 100pt;
}
div#content h2 {
    width: 540pt;
    margin: 0pt auto 20pt;
    font-size: 1em;
}

<?php $this->headStyle()->captureEnd(); ?>
<h1>404</h1>
<h2>Sorry but this page cannot be found. If you typed in an address please make sure it is correct. Hopefully it wasn't one of our links you followed!</h2>