<!--<h1>IMPORTANT NOTICE ABOUT COOKIES</h1>

<p>This notice is designed to provide you with more information about how Bauer 
    Media (the publisher of this website) uses cookies.</p>

<h2>What are Cookies?</h2>

<p>"Cookies" are small files that contain information that a website sends to 
    your computer, laptop or mobile media device's hard drive while you are 
    viewing a website. Each cookie is unique to your web browser and will 
    contain some anonymous information such as unique identifier and the site 
    name and some digits and numbers. It allows a website to remember things 
    like your preference or what's in your shopping basket.</p>

<h2>How does Bauer Media use Cookies?</h2>

<p>Cookies are used by lots of websites to provide features to their users and 
    they are used by Bauer Media to improve its websites and to deliver a better 
    and more personalized and interactive service to you.</p>

<p>Bauer Media also uses persistent cookies, which stay on your computer or 
    mobile media device even after you have gone offline.</p>

<p>Bauer Media will use different types of cookies at various different pages of 
    your use of our websites, these types of cookies include:</p>

<dl>
    <dt>Functionality Cookies</dt>
    <dd><p>These are essential to the running of a Bauer Media website. They 
        include Session cookies, which enable you to carry out essential 
        functions on Bauer Media's websites like maintaining login details for 
        the session or a transaction. Session cookies are not stored on your 
        computer and the information these cookies collect is anonymised and 
        they cannot track your browsing activity on other website. These cookies 
        will expire when you close your web browser session.</p></dd>

    <dt>Third Party Cookies</dt>
    <dd><p>We use a selection of third party tools for performance monitoring, ad 
        serving and social media sharing. The links below provide more 
        information about how these tools use cookies.</p>
        <div>
            Issued by	Cookie type	Information available at
            Nielsen	Performance	http://www.nielsen.com
            Comscore	Performance	http://www.comscore.com
            Piwik	Performance	http://piwik.org
            Google Analytics	Performance	http://www.google.com
            Radioplayer	Performance & Functionality	http://www.radioplayer.co.uk
            AddThis	Performance & Functionality	http://www.addthis.com
            Facebook	Performance & Functionality	https://www.facebook.com
            Twitter	Performance & Functionality	https://twitter.com
            Google+	Performance & Functionality	http://www.google.com/plus/
            Google Adsense	Targeting & Advertising	http://www.google.com/adsense/
            247 Media	Targeting & Advertising	http://www.247media.com
            Adswizz	Targeting & Advertising	http://www.adswizz.com
            AdMob	Targeting & Advertising	http://www.admob.com
            AdTech	Targeting & Advertising	http://www.adtech.com/en/service/cookies.html
            The Rubicon Project	Targeting & Advertising	http://www.rubiconproject.com/privacy/
            Audience Science	Behavioural Targeting	http://www.audiencescience.com/privacy/
        </div>
    </dd>
    <dt>Third party cookies for advertising</dt>
    <dd>
        <p>Many of our websites carry advertising. A certain amount of this 
        advertising is tailored to the individual user, as practice known as 
        "Online Behavioral Advertising" which uses cookies to discover general 
        information about the pages you visit. The tracking system is anonymised 
        and therefore it does not know who you are; it simply uses the limited 
        information available to it to serve adverts to you, which it believes 
        are relevant. It does not collect personal information such as your name, 
        email address postal address or telephone number.</p>
        
        <p>From time to time, Bauer Media may share this annonymised behavioural 
            data with our advertising partners. This could mean that when you 
            are on other websites you are served advertising based on your 
            behaviour across Bauer Media titles or you may be served advertising 
            based on your behaviour on other sites.</p>
        
        <p>Behavioural retargeting is another form of Online Behaviourial 
            Advertising that enables us and some of our advertising partners to 
            show you adverts based on browsing patterns and interactions with 
            the site away from our sites. For example, if you have visited the 
            website of Car Dealership you may start seeing adverts from that 
            same Dealership site displaying special offers or showing you the 
            products that you were browsing. This is allows companies to 
            advertise to website visitors who leave their website without making 
            a purchase.</p>
        
        <p>If you want to opt out of receiving Online Behaviourial Advertising 
            this does not mean that you will no longer receive advertising when 
            you are using our sites. It just means that the advertising you see 
            will not be customised for you. If you would like more information 
            about Onsite behavioural targeting and how to opt out of it, please 
            visit www.youronlinechoices.com</p>
    </dd>
    <dt>Third party cookies for tracking/user analysis</dt>
    <dd>
        <p>Many of our websites also use cookies to track how many individual 
            unique users we have and how often they visit Bauer Media's websites. 
            We use 3rd party companies for this service such as Google Analytics 
            provided by Google.</p>
    </dd>
    <dt>Bauer Media Marketing Cookies</dt>
    <dd>
        <p>These are normally supplied by our approved partners or adverts 
            delivered from Bauer Media's own systems and allow us to serve you 
            adverts that you might be more interested in. This tracking system 
            will log what adverts you see and will cap the number of times you 
            see an advertisement. The data collected is anonymised and therefore 
            the cookies do not know who you are.</p>
    </dd>
</dl>
<h2>What to do if you want to control the use of Cookies?</h2>
<p>You have the ability to accept or decline cookies using your web browser, but 
    please be aware that for some parts of our websites to work you will need to 
    accept cookies. Cookies can be removed or declined by changing your web 
    browser settings. For more information please visit www.allaboutcookies.org 
    and/or www.youronlinechoices.com. Please be aware that this is 3rd party 
    website and as such Bauer Media accept no liability for the instructions 
    given on this site.</p>

<p>If you have any questions about Bauer's policy, please contact 
    dataprotectionofficer@bauermedia.co.uk.</p>


<p>Updated June 2014</p>-->