<h2>IMPORTANT NOTICE ABOUT COOKIES</h2>

<p>This notice is designed to provide you with more information about how 
Low-Emedia (the publisher of this website) uses cookies.</p>

<h2>What are Cookies?</h2>

<p>"Cookies" are small files that contain information that a website sends to 
    your computer, laptop or mobile media device's hard drive while you are 
    viewing a website. Each cookie is unique to your web browser and will 
    contain some anonymous information such as unique identifier and the site 
    name and some digits and numbers. It allows a website to remember things 
    like your preference or what's in your shopping basket.</p>

<h2>How does Low-Emedia use Cookies?</h2>

<p>Cookies are used by lots of websites to provide features to their users and 
    they are used by Low-Emedia to improve its websites and to deliver a better 
    and more personalised and interactive service to you.</p>

<p>Low-Emedia also uses persistent cookies, which stay on your computer or 
    mobile media device even after you have gone offline.</p>

<p>Low-Emedia will use different types of cookies at various different pages of 
    your use of our websites, these types of cookies include:</p>

<dl>
    <dt>Third party cookies for tracking/user analysis</dt>
    <dd>
        <p>Many of our websites also use cookies to track how many individual 
            unique users we have and how often they visit Low-Emedia's websites. 
            We use 3rd party companies for this service such as Google Analytics 
            provided by Google.</p>
    </dd>
    <dt>Low-Emedia Marketing Cookies</dt>
    <dd>
        <p>These are normally supplied by our approved partners or adverts 
            delivered from Low-Emedia's own systems and allow us to serve you 
            adverts that you might be more interested in. This tracking system 
            will log what adverts you see and will cap the number of times you 
            see an advertisement. The data collected is anonymised and therefore 
            the cookies do not know who you are.</p>
    </dd>
</dl>
<h2>What to do if you want to control the use of Cookies?</h2>
<p>You have the ability to accept or decline cookies using your web browser, but 
    please be aware that for some parts of our websites to work you will need to 
    accept cookies. Cookies can be removed or declined by changing your web 
    browser settings. For more information please visit www.allaboutcookies.org 
    and/or www.youronlinechoices.com. Please be aware that this is 3rd party 
    website and as such Low-Emedia accept no liability for the instructions 
    given on this site.</p>

<p>If you have any questions about Low-Emedia's policy, please contact 
    info@low-emedia.com.</p>


<p>Updated December 2014</p>