<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Flicks From The Past!'); ?>

        <?php 
        $this->headMeta()
            ->setCharset('UTF-8')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('Content-Type','text/html')
            ->appendHttpEquiv('Content-Language', 'en-GB')
            ;
        
        $this->headLink()
                ->prependStylesheet($this->basePath('css/fonts.css'))
                ->appendStylesheet($this->basePath('css/layout.css'))
                ->appendStylesheet($this->basePath('css/mainSearch.css'))
                ;
        
        $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery-1.10.2.min.js')
                ;
        ?>
        
        <?php $this->headScript()->captureStart(); ?>
        $(function() {
            $('header h1').click(function() {
                location.href = '<?php echo $this->url('home'); ?>';
            });
            
            $('form#mainSearch input[type=submit]').click(function(event) {
                if (!$('form#mainSearch input[name=search]').val()) {
                    event.preventDefault();
                }
            });
        });
        <?php $this->headScript()->captureEnd(); ?>
        
        <?php
        echo $this->headMeta() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        echo $this->headStyle() . "\n";
        ?>
    </head>
    <body>
          <?php if ($this->GoogleAnalytics()): ?>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-15536564-4', 'auto');
          ga('require', 'displayfeatures');
          ga('require', 'linkid', 'linkid.js');
          ga('send', 'pageview');
        </script>
          <?php endif; ?>
        <div id="main">
            <header>
                <h1>Flicks From The Past!</h1>
                <?php echo $this->form()->openTag($this->MainSearch()->setAttributes(array('method' => 'get', 'action' => $this->url('search')))); ?>
                <?php echo $this->formRow($this->MainSearch()->get('search')); ?>
                <?php echo $this->formRow($this->MainSearch()->get('type')); ?>
                <?php echo $this->formElement($this->MainSearch()->get('submit')); ?>
                <?php echo $this->form()->closeTag(); ?>
                <div style='float: right;'>
                    <a href='https://www.youtube.com/channel/UCuJZlbQ9iB5VoFCWZYGY_Jg' target='_blank'><img src='/images/YouTube-logo-light.png' border="0" style='width: 100px; float: right;margin: 3pt 0pt;' /></a>
                    <a href='https://twitter.com/FlicksFromPast' target='_blank'><img src='/images/Twitter_logo_white.png' border="0" style='width: 40px; float: right; margin: 15pt 0pt 10pt 10pt' /></a>
                    <a href='https://www.facebook.com/flicksfromthepast' target='_blank'><img src='/images/FB-f-Logo__blue_50.png' border="0" style='width: 35px; float: right; border: 1pt solid #9f9f9f; border-radius: 0.5em; margin: 11pt 6pt' /></a>
                </div>
            </header>
            <div id="content" style='clear: both;'>
            <?php echo $this->content . "\n"; ?>
            </div>
        
            <footer>
                <p>&copy;<?php echo date('Y'); ?> <span class='company'>Low-Emedia</span></p>
            </footer>
        </div>
    </body>
</html>
