<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Flicks From The Past!', 'PREPEND'); ?>

        <?php 
        $this->headMeta()
            ->appendName("viewport", "width=device-width, initial-scale=1.0")
            ->setCharset('UTF-8')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('Content-Type','text/html')
            ->appendHttpEquiv('Content-Language', 'en-GB')
            ;
        
        $this->headLink()
                ->prependStylesheet($this->basePath('css/fonts.css'))
                ->appendStylesheet($this->basePath('css/layout.css'))
                ;
        
        $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery-1.10.2.min.js')
                ;
        ?>
        
        <?php $this->headScript()->captureStart(); ?>
        <?php $this->headScript()->captureEnd(); ?>
        
        <?php $this->headStyle()->captureStart(); ?>
        body {
            font-size: 100%;
        }
        
        #main {
            width: 850pt;
            margin: 0 auto;
        }
        
        header div.top {
            /*width: 139px;*/
            height: 45pt;

            border-bottom: 1px solid #e0e0e0;
        }

        div.section {
            position: relative;

            height: 89pt;
        }

        div.sectionTop {
            width: 144pt;
            background-color: #d3222a;
            height: 40pt;
            border-bottom: 1px solid #ba1e25;
            background-image: url('../images/white-on-black-logo.png');
            background-size: 162px 30px;
            background-position: 12pt 8pt;
            background-repeat: no-repeat;
            float: left;
            margin: 5pt 0 0 35pt;
        }
        
        input[type=text] {
            float: left;
            width: 160pt;
            height: 10pt;
            display: block;
            border: 1pt solid #e0e0e0;
            padding: 10pt;
            font-size: 0.9em;
            border-radius: 5pt 0pt 0pt 5pt;
            border-right: none;
            background-color: #f2f2f2;
            margin: 10pt 0pt 0pt 10pt;
        }

        div#searchBtn {
            float: left;
            font-family: 'Glyphicons Halflings' !important;
            border: 1pt solid #e0e0e0;
            border-left: none;
            width: 20pt;
            height: 10pt;
            padding: 8pt 10pt 12pt;
            background-color: #f2f2f2;
            border-radius: 0pt 5pt 5pt 0pt;
            margin: 10pt 10pt 0pt 0pt;
        }
        div#searchBtn:after {

            content:"\e003";
        }
        
        div.bottom {
        }
        
        div#menu {
            clear: both;
            float: left;
            width: 144pt;
            color: #fff;
            height: 30pt;
            font-family: sans-serif;
            text-decoration: none;
            background-color: #d3222a;
            margin: 0 0 0 35pt;
        }

        div#menu p {
            padding: 8pt;
        }

        div#menu:hover {
            background-color: #000;

        }
        
        nav#mainNav {
            width: 110pt;
            float: left;
            background-color: #fff;
        }

        nav#mainNav ul {
            width: 311pt;
            list-style-type: none;
            height: 31pt;
        }

        nav#mainNav ul li {
            padding: 8pt 15pt;
            float: left;
            /**/
        }

        nav#mainNav ul li a {
            text-decoration: none;
            color: #d3222a;
            font-size: 0.8em;
        }

        nav#mainNav ul li a:hover {
            color: #000;
        }
        
        div#body {
            clear: both;
            margin: 10pt 15pt;
            padding: 0pt 10pt;
        }
        
        <?php $this->headStyle()->captureEnd(); ?>
        
        <?php
        echo $this->headMeta() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        echo $this->headStyle() . "\n";
        ?>
    </head>
    <body>
        <div id="main">
            <header>
                <div class="top">
                    <div class="sectionTop"></div>
                    <input id="search-input" type="text" maxlength="60" placeholder="Search" name="query" autocomplete="off">
                    <div id="searchBtn"></div>
                </div>
                <div class="bottom">
                    <div id="menu"><p>Menu</p></div>
                    <nav id="mainNav">
                    <ul>
                        <li><a href="#">News</a></li>
                        <li><a href="#">Features</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </nav>
                </div>
                <div style="clear: both;"></div>
<!--                -->
            </header>
            <div id="body">
                <?php echo $this->content . "\n"; ?>
            </div>
        </div>
    </body>
</html>
