<?php 
$title = html_entity_decode($article->title);
$this->headTitle(" - {$title}");
$this->headMeta()->appendName('description', $article->summary);

$this->headLink()
        ->appendStylesheet($this->basePath('css/article.css'))
        ; 
?>
<?php $this->headScript()->captureStart(); ?>
$(function() {
    $('div.articles article h3 a').click(function(event) {
        event.preventDefault();
    });
    $('div.articles article').click(function() {
        location.href = $(this).children('h3').children('a').attr('href');
    });
});
<?php $this->headScript()->captureEnd(); ?>
<article id='main' style="float: left;">
    <h2><?php echo $article->title; ?></h2>
    <h3><?php echo $article->subtitle; ?></h3>
    <h3>Written By: <?php echo $article->author; ?> </h3>
    <p class='date'>Date: <?php echo $this->DisplayDate($article->publishDate); ?></p>
    <?php echo $article->content; ?>
    <?php if (!strstr($article->originalUrl, 'http://www.flicksfromthepast.com')): ?>
    <p>Original Link: <a href="<?php echo $article->originalUrl; ?>" target="_blank"><?php echo $article->originalUrl; ?></a></p>
    <?php endif; ?>
    <?php if ($showImage): ?>
    <?php foreach ($article->articleImages as $image): ?>
    <?php $data = getimagesize($image->url); ?> 
    <img src='<?php echo $image->url;?>' style='width:<?php echo $data[0] < 650?$data['width']:'100%' ?>;'>
    <?php endforeach; ?>
    <?php endif; ?>
    <?php if ($showMedia): ?>
    <?php foreach ($article->articleMedia as $media): ?>
    <?php echo $media->code;?>
    <?php endforeach; ?>
    <?php endif; ?>
    
    
</article>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
$('article').append('<div class="fb-comments" style="padding: 20pt 45pt 10pt;" data-href="' + location.href + '" data-numposts="5" data-colorscheme="light"></div>');
$('article p.date').after('<div class="fb-like" style="margin: 10pt 0pt 0pt;" data-href="' + location.href + '" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>');
</script>


<?php if ($this->products): ?>
<?php echo $this->partial('partials/amazonProducts.phtml', array('products' => $this->products, 'title'=>'Related Amazon Products')); ?>
<?php endif; ?>

<?php if ($this->news): ?>
<div id="news" class="articles">
    <h2>Latest News</h2>
    <?php foreach ($this->news as $newsArticle): ?>
    <article>
        <h3><a href="<?php echo $this->url('article/profile', array('slug' => $newsArticle->slug)); ?>"><?php echo $newsArticle->title; ?></a></h3>
        <p><?php echo trim($newsArticle->summary); ?>...</p>
        <p class="date">Date: <?php echo $this->DisplayDate($newsArticle->publishDate); ?></p>
    </article>
    <?php endforeach; ?>
    <p class="more">See More...</p>
</div>
<?php endif; ?>