<?php 
$title = html_entity_decode($article->title);
$this->headTitle("{$title} - ");
$this->headMeta()->appendName('description', $article->summary);

$this->headLink()
        ->appendStylesheet('/css/article.css')
        ; 
?>
<?php $this->headScript()->captureStart(); ?>
$(function() {
    $('div.articles article h3 a').click(function(event) {
        event.preventDefault();
        //alert('here');
    });
    $('div.articles article').click(function() {
        location.href = $(this).children('h3').children('a').attr('href');
    });
    
});
<?php $this->headScript()->captureEnd(); ?>
<article id='main' style="float: left;">
    <h2><?php echo $article->title; ?></h2>
    <h3><?php echo $article->subtitle; ?></h3>
    <h3>Written By: <?php echo $article->author; ?> </h3>
    <p class='date'>Date: <?php echo $this->DisplayDate($article->publishDate); ?></p>
    <?php echo $article->content; ?>
    <?php if (!strstr($article->originalUrl, 'http://www.flicksfromthepast.com')): ?>
    <p>Original Link: <a href="<?php echo $article->originalUrl; ?>" target="_blank"><?php echo $article->originalUrl; ?></a></p>
    <?php endif; ?>
</article>

<div id="news" class="articles">
    <h2>Latest News</h2>
    <?php foreach ($this->news as $newsArticle): ?>
    <article>
        <h3><a href="<?php echo $this->url('article/profile', array('slug' => $newsArticle->slug)); ?>"><?php echo $newsArticle->title; ?></a></h3>
        <p><?php echo trim($newsArticle->summary); ?>...</p>
        <p class="date">Date: <?php echo $this->DisplayDate($newsArticle->publishDate); ?></p>
    </article>
    <?php endforeach; ?>
    <p class="more">See More...</p>
</div>
<!--
<div id="related" class="articles" style="width: 515pt; float: left;">
    <h2>Latest Related Articles</h2>

    <article style="float: left;">
        <h3>Something</h3>
        <p>Something...</p>
        <p class="date">Date: <?php echo $this->DisplayDate('2014-01-01'); ?></p>
    </article>
    <article style="float: left;">
        <h3>Something</h3>
        <p>Something...</p>
        <p class="date">Date: <?php echo $this->DisplayDate('2014-01-01'); ?></p>
    </article>
    <article style="float: left;">
        <h3>Something</h3>
        <p>Something...</p>
        <p class="date">Date: <?php echo $this->DisplayDate('2014-01-01'); ?></p>
    </article>
    <article style="float: left;">
        <h3>Something</h3>
        <p>Something...</p>
        <p class="date">Date: <?php echo $this->DisplayDate('2014-01-01'); ?></p>
    </article>
    <p class="more" style="clear: both;">See More...</p>
</div>

<div id="relatedProducts" class="articles" style="width: 515pt; float: left;">
    <h2>Latest Related Products</h2>

    <article style="float: left;">
        <h3>Something</h3>
        <p>Something...</p>
        <p class="date">Date: <?php echo $this->DisplayDate('2014-01-01'); ?></p>
    </article>
    <article style="float: left;">
        <h3>Something</h3>
        <p>Something...</p>
        <p class="date">Date: <?php echo $this->DisplayDate('2014-01-01'); ?></p>
    </article>
    <article style="float: left;">
        <h3>Something</h3>
        <p>Something...</p>
        <p class="date">Date: <?php echo $this->DisplayDate('2014-01-01'); ?></p>
    </article>
    <p class="more" style="clear: both;">See More...</p>
</div>
-->