<?php
$this->headLink()
        ->appendStylesheet($this->basePath('css/articles.css'))
        ;
?>
<?php $this->headScript()->captureStart(); ?>
$(function() {
    $('div.articles article h3 a').click(function(event) {
        event.preventDefault();
    });
    $('div.articles article').click(function() {
        location.href = $(this).children('h3').children('a').attr('href');
    });
});
<?php $this->headScript()->captureEnd(); ?>

<div class="articles" style="width: 515pt; float: left;">
    <h2><?php echo ucfirst($this->type); ?></h2>
    <?php foreach ($this->articles as $article): ?>
    <article style='clear: both;'>
        <?php if (count($article->articleImages) > 0): ?>
        <?php $image = current($article->articleImages); ?>
        <?php if (file_exists($image->url) || strstr($image->url, 'http')): ?>
        <img src='<?php echo $image->url; ?>' style='width: 100pt; float: left; margin-right: 10pt;'>
        <?php endif; ?>
        <?php endif; ?>
        <h3><a href='<?php echo $this->url('article/profile', array('slug' => $article->slug)); ?>'><?php echo $article->title; ?></a></h3>
        <p><?php echo trim($article->summary); ?>...</p>
        <p class="date">Date: <?php echo $this->DisplayDate($article->publishDate); ?></p>
        <div style='clear: both'></div>
    </article>
    <?php endforeach; ?>
</div>

<div style="width: 120pt; float: right; margin: 10pt; padding: 0pt 40pt; box-shadow: 0pt 1pt 2pt #9f9f9f;border-radius: 0.5em;">
    <SCRIPT charset="utf-8" type="text/javascript" src="http://ws-eu.amazon-adsystem.com/widgets/q?rt=tf_cw&ServiceVersion=20070822&MarketPlace=GB&ID=V20070822%2FGB%2Flowemedi-21%2F8010%2F3222cc9a-8cc7-4fef-8a36-8b80bfe6cea8&Operation=GetScriptTemplate"> </SCRIPT> <NOSCRIPT><A HREF="http://ws-eu.amazon-adsystem.com/widgets/q?rt=tf_cw&ServiceVersion=20070822&MarketPlace=GB&ID=V20070822%2FGB%2Flowemedi-21%2F8010%2F3222cc9a-8cc7-4fef-8a36-8b80bfe6cea8&Operation=NoScript">Amazon.co.uk Widgets</A></NOSCRIPT>
</div>
