<?php
$this->headLink()
        ->appendStylesheet($this->basePath('css/articles.css'))
        ->appendStylesheet($this->basePath('css/breadcrumbs.css'))
        ;
?>
<?php $this->headScript()->captureStart(); ?>
$(function() {
    $('div.articles article h3 a').click(function(event) {
        event.preventDefault();
    });
    $('div.articles article').click(function() {
        location.href = $(this).children('h3').children('a').attr('href');
    });
});
<?php $this->headScript()->captureEnd(); ?>
<div class="breadcrumbs">
    <p>
        <a href='<?php echo $this->url('home'); ?>'>Home</a>
        <?php if ($this->type == 'news'): ?>
         > <a href='<?php echo $this->url('articles', array('type' => 'news')); ?>'>News</a>
        <?php elseif ($this->type == 'features'): ?>
         > <a href='<?php echo $this->url('articles', array('type' => 'features')); ?>'>Features</a>
        <?php elseif ($this->type == 'reviews'): ?>
         > <a href='<?php echo $this->url('articles', array('type' => 'reviews')); ?>'>Reviews</a>
        <?php endif; ?> 
    </p>
</div>
<div class="articles" style="width: 515pt; float: left;">
    <h2><?php echo ucfirst($this->type); ?></h2>
    <?php foreach ($this->articles as $article): ?>
    <article style='clear: both;'>
        <?php if (isset($article->image)): ?>
        <?php $image = $article->image; ?>
            <img src='<?php echo $image; ?>' style="float: left; width: 100pt; margin-right: 10pt;">
        <?php endif; ?>
        <h3><a href='<?php echo $this->url('article/profile', array('slug' => $article->slug)); ?>'><?php echo $article->title; ?></a></h3>
        <p><?php echo trim($article->summary); ?>...</p>
        <p class="date">Date: <?php echo $this->DisplayDate($article->publishDate); ?></p>
        <div style='clear: both'></div>
    </article>
    <?php endforeach; ?>
</div>
<?php echo $this->partial('partials/amazonProducts.phtml', array('products' => $this->products, 'title'=>'Top Seller Amazon Products')); ?>