<?php 
$this->headScript()
        ->appendFile($this->basePath('js/slides.js')); 

$this->headLink()
        ->appendStylesheet($this->basePath('css/sleek/sections.css'))
        ->appendStylesheet($this->basePath('css/sleek/slideshows.css'))
        ;
?>
<?php $this->headStyle()->captureStart(); ?>


<?php $this->headStyle()->captureEnd(); ?>

<?php $this->headScript()->captureStart(); ?>

var HeadlineSlideshow = function() {
    var slideWidth = $('div.headline').width();
    var numberOfSlides = 0;
    var slideContent = 0;
    
    this.execute = function() {
        $('div#headlines').width(calculateWidth());
    }
    
    var calculateWidth = function() {
        
        slideContent = Math.floor($('div#featured').width() / slideWidth);
    
        numberOfSlides = $('div.headline').length / slideContent;
        
        width = calculate();
        
        if ($('div#featured').width() < width) {
            //numberOfSlides = numberOfSlides - 1
            width = calculate();
        }
        return width;
    }
    
    var calculate = function() {
        var width = parseInt($('div.headline').width() * slideContent);
        
        $('div.headline').css('margin-left', '5px');
        $('div.headline').css('margin-right', '5px');
        
        width = width + ((5 * slideContent) * 2);
        
        $('p.controls').unbind("click");
        
        var content = new SlideContent({
            currentPosition : 0,
            slideWidth : width,
            numberOfSlides : numberOfSlides,
            controls : $('p.controls'),
            slideInner : $('div#slideshow')
        });

        content.enableControls();
        return width;
    }
    
    this.resize = function() {
    
    
        $(window).bind('resize', function(e) {
            window.resizeEvt;
            $(window).resize(function()
            {
                clearTimeout(window.resizeEvt);
                window.resizeEvt = setTimeout(function()
                {
                    $('div#headlines').width(calculateWidth());
                }, 100);
            });
        });
        
//        $(window).resize(function() {
//            $('div#headlines').width(calculateWidth());
//        });
    }
    
}

$(function() {
    var slideshow = new HeadlineSlideshow();
    slideshow.execute();
    slideshow.resize();


    
});


<?php $this->headScript()->captureEnd(); ?>

<?php 
$this->headLink()
//        ->appendStylesheet($this->basePath() . 'css/components.css')
//        ->appendStylesheet($this->basePath() . 'css/columns.css')
        ; 
?>

    <div id="featured">
        <div id="headlines">
            <div id='slideshow'>
                <div class="headline" style="background-image: url('images/AVENGERS-TRIO_650.jpg');">
                    <div class='content'>
                        <h2>Something</h2>
                        <p>Something else</p>
                    </div>
                </div>
                <div class="headline" style="background-image: url('images/NEW-ENTERPRISE-CREW_650_002.jpg');">
                    <div class='content'>
                        <h2>Something</h2>
                        <p>Something else</p>
                    </div>
                </div>
                <div class="headline" style="background-image: url('images/PREDATORS_650_XVI.jpg');">
                    <div class='content'>
                        <h2>Something</h2>
                        <p>Something else</p>
                    </div>
                </div>
                <div class="headline" style="background-image: url('images/PREDATORS_650_XVI.jpg');">
                    <div class='content'>
                        <h2>Something</h2>
                        <p>Something else</p>
                    </div>
                </div>
                <div class="headline" style="background-image: url('images/NEW-ENTERPRISE-CREW_650_002.jpg');">
                    <div class='content'>
                        <h2>Something</h2>
                        <p>Something else</p>
                    </div>
                </div>
                <div class="headline" style="background-image: url('images/AVENGERS-TRIO_650.jpg');">
                    <div class='content'>
                        <h2>Something</h2>
                        <p>Something else</p>
                    </div>
                </div>
            </div>
            <p class='controls' id='previous'>&#xe091;</p>
            <p class='controls' id='next'>&#xe092;</p>

        </div>
    </div>
    <div id="articles" style="float: left;  width: 390pt;">
        <h2>Latest Articles</h2>
        <?php $count = 0; ?>
        <pre>
        <?php if (isset($this->articles->features)): ?>
        <?php foreach ($this->articles->features as $feature): ?>
        <?php if ($count > 6): ?>
        <?php break; ?>
        <?php endif; ?>
        <article>
            <img src="<?php echo $this->basePath('images/ghostbusters.jpg'); ?>" style="width: 150px; height: 85px; float: left; margin: 5pt 5pt" />
            <h3><a href="<?php echo $this->url('article/profile',array('slug' => $feature->slug)); ?>"><?php echo $feature->title; ?></a></h3>
            <p><?php echo trim($feature->summary); ?>...</p>
            <p style="clear: both;">Posted on: <time><?php echo $this->DisplayDate($feature->publishDate); ?></time> Source:</p>
        </article>
        <?php $count++; ?>
        <?php endforeach; ?>
        <?php endif; ?>
        <div style="clear: both;">
            <p><a href="#">See All Latest Articles...</a></p>
        </div>
    </div>
    <div id="reviews" style="clear: none; float: right; width: 390pt;">
        <h2>Latest Reviews</h2>
        <?php $count = 0; ?>
        <?php foreach ($this->articles->reviews as $review): ?>
        <?php if ($count > 6): ?>
        <?php break; ?>
        <?php endif; ?>
        <article>
            <img src="<?php echo $this->basePath('images/ghostbusters.jpg'); ?>" style="width: 150px; height: 85px; float: left; margin: 5pt 5pt" />
            <h3><a href="<?php echo $this->url('article/profile',array('slug' => $review->slug)); ?>"><?php echo $review->title; ?></a></h3>
            <p><?php echo trim($review->summary); ?>...</p>
            <p style="clear: both;">Posted on: <time><?php echo $this->DisplayDate($review->publishDate); ?></time> Source:</p>
        </article>
        <?php $count++; ?>
        <?php endforeach; ?>
        <div style="clear: both;">
            <p><a href="#">See All Latest Reviews...</a></p>
        </div>
    </div>
    <div id="news">
        <h2>Latest News From The Web</h2>
        <?php foreach ($this->articles->news as $news): ?>
        <article>
            <h3><a href="<?php echo $this->url('article/profile',array('slug' => $news->slug)); ?>"><?php echo $news->title; ?></a></h3>
            <p><?php echo trim($news->summary); ?>...</p>
            <p>Posted on: <time><?php echo $this->DisplayDate($news->publishDate); ?></time> Source:</p>
        </article>
        <?php endforeach; ?>
        <div style="clear: both;">
            <p><a href="<?php echo $this->url('articles'); ?>">See All Latest Articles...</a></p>
        </div>
    </div>

<!--<section id="col2">
    <section>
        <h2>Reviews</h2>
        <ul>
            <li><p><strong>Transformers</strong><br />Posted on: <time>01/01/2001</time></p></li>
            <li><p><strong>Star Wars</strong><br />Posted on: <time>01/01/2001</time></p></li>
            <li><p><strong>Back to the Future</strong><br />Posted on: <time>01/01/2001</time></p></li>
            <li><p><strong>Dr. Strangelove</strong><br />Posted on: <time>01/01/2001</time></p></li>
            <li><p><strong>Star Trek</strong><br />Posted on: <time>01/01/2001</time></p></li>
        </ul>
        <div>
            <p><a href="#">See All Latest Reviews...</a></p>
        </div>
    </section>
    <section>
        <h2>Trailers</h2>
        <ul>
            <li><p><strong>Transformers</strong><br />Posted on: <time>01/01/2001</time></p></li>
            <li><p><strong>Star Wars</strong><br />Posted on: <time>01/01/2001</time></p></li>
            <li><p><strong>Back to the Future</strong><br />Posted on: <time>01/01/2001</time></p></li>
            <li><p><strong>Dr. Strangelove</strong><br />Posted on: <time>01/01/2001</time></p></li>
            <li><p><strong>Star Trek</strong><br />Posted on: <time>01/01/2001</time></p></li>
        </ul>
        <div>
            <p><a href="#">See All Latest Trailers...</a></p>
        </div>
    </section>
</section>-->
